### ISSUE TITLE
Wrong script snapshot version, expected '...' found '...'

### ISSUE THREAD

**Issue by damondouglas** [damondouglas/hello-shelf-snapshot#1]
@Scorpiion Deploying this repo on sourcevoid results in the following error in the console:

`Wrong script snapshot version, expected '181c54397e255f0b57b3cbca6f22607a' found '67ac118c5ca5a680109da82693316e0c'`

I had previously run a successful snapshot from another repo, version `181c54397e255f0b57b3cbca6f22607a`.  But from then on I continue to receive this error.  I even deleted the pool and started over.

**Comment by Scorpiion** [comment]
Hi, what Dart version do you use locally?

**Comment by Scorpiion** [comment]
I guess it's worth mentioning that while it is possible to deploy a prebuilt snapshot that is not the intended way to deploy, but in your case with a private git dependency it might be the easiest way atm.

When you deploy like this, you don't even need to run pub get, so your sourcevoid.yaml can look like this:

```
runtime: dart
version: latest

start: dart bin/server.snapshot
```

Or even like this (version will get the default "latest" value):
```
runtime: dart
start: dart bin/server.snapshot
```

If you want a specific Dart version, just specify it:
```
runtime: dart
version: 1.17.0

start: dart bin/server.snapshot
```

**Comment by Scorpiion** [comment]
Hi again...

I think I can confirm that it works if I deploy using the right Dart version and I get that error if I setup a different (older) Dart version.

I have Dart version 1.17.1 locally, and for me these work:
```
runtime: dart
start: dart bin/server.snapshot
```
```
runtime: dart
version: 1.17.1
start: dart bin/server.snapshot
```

Using Dart version 1.16.0 however, then I get that same error as you described:
```
runtime: dart
version: 1.16.0
start: dart bin/server.snapshot
```

**Comment by Scorpiion** [comment]
And to give some context, one of the downsides with snapshots is that they are not guaranteed to work across Dart VM versions, they may or may not do so. Therefor you should make sure to have the same version if you use snapshots, either by using the latest version both locally and on Sourcevoid or to specify the version you use.

**Comment by damondouglas** [comment]
I guess its a good idea to specify a specific version in the `sourcevoid.yaml` in this case instead of using `version: any`.

**Comment by Scorpiion** [comment]
Yes, I think we can say that as a general rule if you use snapshots you should explicitly specify the version. It just hit me that if you have a long running app deployed using a snapshot, and then there is a new Dart version release, then you want to make sure your app stays on the old Dart version until you have deployed a new updated snapshot. 

Again as I said before, deploying snapshots is not optimal, but if you set the version it should work great no matter if there is a new Dart version released.
